# Generated by Django 4.0.4 on 2022-05-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='skill_level',
        ),
    ]
